language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - "$HOME/.npm"
jobs:
  fast_finish: true
  include:
    - stage: root
      install:
        - npm ci
    - stage: backend
      install:
        - cd ./backend
        - npm ci
    - stage: frontend
      install:
        - cd ./frontend
        - npm ci
    - stage: Run Linter
      script:
         - npm run lint
script: echo "npm test temporarily disabled"